<a href="https://colab.research.google.com/github/ektgadcursos-crypto/Intento-de-chatbot/blob/main/EvaluacionE2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import requests
import pandas as pd
import io
import numpy as np

# ============================================================
#  CONFIGURACIÓN DE LA API DE AEMET
# ============================================================

api_key = input("🔑 Introduce tu API Key de AEMET: ")

url_aemet = "https://opendata.aemet.es/opendata/api/observacion/convencional/todas"
headers = {'cache-control': "no-cache", 'api_key': api_key}

df = pd.DataFrame()  # Creamos un DataFrame vacío por seguridad

# ============================================================
#  PETICIÓN DE DATOS A AEMET
# ============================================================

r1 = requests.get(url_aemet, headers=headers)

if r1.status_code == 200:
    data_url = r1.json().get('datos')
    raw_data = requests.get(data_url).json()
    df = pd.DataFrame(raw_data)

    print("Columnas originales recibidas:", df.columns.tolist())

    # ============================================================
    #  RENOMBRADO DE COLUMNAS SEGÚN LA ACTIVIDAD
    # ============================================================

    mapeo_nombres = {
        'hr': 'humedad', 'h': 'humedad',
        'ta': 'temp', 'tam': 'temp', 'tmed': 'temp'
    }

    df = df.rename(columns=mapeo_nombres)

    # Si faltan columnas esenciales, las creamos con valores simulados
    if 'humedad' not in df.columns:
        df['humedad'] = np.random.uniform(40, 80, len(df))

    if 'temp' not in df.columns:
        df['temp'] = np.random.uniform(18, 30, len(df))

else:
    print("❌ Error de conexión. Revisa tu API Key.")
    print("⚠️ Usando datos simulados para continuar la práctica.")

    df = pd.DataFrame({
        'humedad': np.random.uniform(30, 90, 50),
        'temp': np.random.uniform(10, 35, 50)
    })

# ============================================================
#  CREACIÓN DE SENSORES QUÍMICOS (PM2.5 y CO2)
#  (Siempre se crean aquí, independientemente de la API)
# ============================================================

df['pm25'] = np.random.uniform(-10, 150, len(df))  # Incluye errores adrede
df['co2'] = np.random.uniform(-100, 600, len(df))  # Incluye errores adrede

# ============================================================
#  ETIQUETADO AUTOMÁTICO DEL ESTADO DEL AIRE
# ============================================================

def etiquetar_aire(row):
    if row['pm25'] > 80:
        return "Episodio de Calima"
    if row['co2'] > 450:
        return "Polución Urbana"
    return "Aire Limpio"

df['estado'] = df.apply(etiquetar_aire, axis=1)

# ============================================================
#  LIMPIEZA CRÍTICA DEL DATASET (CE 2.4)
# ============================================================

# 1. Eliminar CO2 negativo (fallo de sensor)
df = df[df['co2'] >= 0]

# 2. Eliminar picos falsos de PM2.5 cuando humedad > 90%
df = df[~((df['humedad'] > 90) & (df['pm25'] > 100))]

# 3. Eliminar duplicados y nulos
df = df.dropna().drop_duplicates()

print(f"🧹 Dataset limpio. Registros restantes: {len(df)}")

# ============================================================
#  VERIFICACIÓN DE SEGURIDAD: EVITAR DATAFRAME VACÍO
# ============================================================

if len(df) < 20:
    print("⚠️ El dataset quedó demasiado pequeño tras la limpieza.")
    print("🔄 Generando un dataset educativo simulado para continuar la práctica...")

    df = pd.DataFrame({
        'pm25': np.random.uniform(5, 150, 200),
        'co2': np.random.uniform(300, 700, 200),
        'humedad': np.random.uniform(20, 80, 200),
        'temp': np.random.uniform(15, 35, 200)
    })

    # Re-etiquetar
    df['estado'] = df.apply(etiquetar_aire, axis=1)

    print("✅ Dataset regenerado correctamente.")


# ============================================================
#  ENTRENAMIENTO DEL MODELO (Random Forest)
# ============================================================

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

# Variables de entrada (X) y salida (y)
X = df[['pm25', 'co2', 'humedad', 'temp']]
y = df['estado']

# División 70/30
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=42
)

# Entrenamiento
modelo_airguard = RandomForestClassifier(n_estimators=100)
modelo_airguard.fit(X_train, y_train)

# Predicción
y_pred = modelo_airguard.predict(X_test)

print("📊 MATRIZ DE CONFUSIÓN:")
print(confusion_matrix(y_test, y_pred))

print("\n📋 REPORTE DE PRECISIÓN:")
print(classification_report(y_test, y_pred))

# ============================================================
#  TEST DE ESTRÉS (5 REGISTROS FRONTERA)
# ============================================================

test_estres = pd.DataFrame([
    [110.0, 380.0, 15.0, 28.0],
    [45.0, 550.0, 60.0, 18.0],
    [10.0, 400.0, 45.0, 22.0],
    [90.0, 410.0, 10.0, 32.0],
    [120.0, 390.0, 12.0, 30.0]
], columns=['pm25', 'co2', 'humedad', 'temp'])

predicciones_finales = modelo_airguard.predict(test_estres)

print("🧐 Clasificación de registros frontera:")
print(predicciones_finales)


🔑 Introduce tu API Key de AEMET: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJla3RnYWQuY3Vyc29zQGdtYWlsLmNvbSIsImp0aSI6ImRhMDZhZGE1LWVkMzQtNDg1NS1hNDBiLTZlMmYxMWVlOGIzMyIsImlzcyI6IkFFTUVUIiwiaWF0IjoxNzc1NzI1OTQ4LCJ1c2VySWQiOiJkYTA2YWRhNS1lZDM0LTQ4NTUtYTQwYi02ZTJmMTFlZThiMzMiLCJyb2xlIjoiIn0.GxccePdINGGFiPOZHONQGCSj8Jul1yJBfQPXFe1oplE
Columnas originales recibidas: ['idema', 'lon', 'fint', 'prec', 'alt', 'vmax', 'vv', 'dv', 'lat', 'dmax', 'ubi', 'hr', 'tamin', 'ta', 'tamax', 'pres', 'stdvv', 'ts', 'pres_nmar', 'tpr', 'vis', 'stddv', 'inso', 'tss5cm', 'psoltp', 'pliqt', 'rviento', 'vmaxu', 'dvu', 'pacutp', 'vvu', 'stdvvu', 'stddvu', 'dmaxu', 'tss20cm', 'geo850', 'geo925', 'nieve', 'geo700']
🧹 Dataset limpio. Registros restantes: 0
⚠️ El dataset quedó demasiado pequeño tras la limpieza.
🔄 Generando un dataset educativo simulado para continuar la práctica...
✅ Dataset regenerado correctamente.
📊 MATRIZ DE CONFUSIÓN:
[[11  0  0]
 [ 0 29  0]
 [ 1  0 19]]

📋 REPORTE DE PRECISIÓN:
                    precis